/**
 * Real authored source for HyperFrames components, loaded on demand.
 *
 * The manifest carries only names, titles, and one-line descriptions. Asking a
 * model to "implement browser-device-stage" from that sentence is asking it to
 * reconstruct 25KB of token-driven chrome from thirty words, which it cannot
 * do — so it invented its own markup on every generation and marked it with the
 * component's name. Handing it the actual contract, CSS, markup, and
 * choreography is what makes retrieval mean anything.
 *
 * The bundle is generated by `npm run registry:build-source` and imported
 * lazily so its ~900KB never lands in the editor's initial payload.
 */

type ComponentSourceBundle = Readonly<Record<string, string>>;

let bundle: ComponentSourceBundle | null = null;
let inFlight: Promise<ComponentSourceBundle> | null = null;

async function loadBundle(): Promise<ComponentSourceBundle> {
  if (bundle) return bundle;
  inFlight ??= import("../../registry/component-source.json")
    .then((module) => {
      bundle = (module.default ?? module) as ComponentSourceBundle;
      return bundle;
    })
    .catch(() => {
      // A missing bundle must not block generation: the request falls back to
      // the name-and-description brief that shipped before source injection.
      bundle = {};
      return bundle;
    });
  return inFlight;
}

export interface ComponentSource {
  readonly name: string;
  readonly source: string;
}

/**
 * Returns authored source for the named components, in the order asked for and
 * skipping any the bundle does not carry.
 */
export async function getComponentSource(
  names: readonly string[],
): Promise<readonly ComponentSource[]> {
  if (names.length === 0) return [];
  const loaded = await loadBundle();
  const found: ComponentSource[] = [];
  for (const name of names) {
    const source = loaded[name];
    if (source) found.push({ name, source });
  }
  return found;
}
