export const MOTIONLY_PROMO_SOURCE_DURATION = 39;
export const MOTIONLY_PROMO_DURATION = 58.5;
export const MOTIONLY_PROMO_TIME_SCALE =
  MOTIONLY_PROMO_SOURCE_DURATION / MOTIONLY_PROMO_DURATION;
export const MOTIONLY_PROMO_RETIME_FACTOR =
  MOTIONLY_PROMO_DURATION / MOTIONLY_PROMO_SOURCE_DURATION;
